# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'release/**'

jobs:
  build:
    strategy:
      matrix:
        host: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        
    runs-on: ${{matrix.host}}
    name: Build on ${{matrix.host}}
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal